export const poems = [
  {
    author: "Tom Kuhn",
    title: "If From this Soulful Heart",
    poemLines: [
      "If from this soulful heart one little rose",
      "Might bloom its petal'd hope of fragrant rays",
      "Into the tired tangled frazzled haze",
      "Of one bewildered mind; then I suppose",
      "This life is not a fragmentary close",
      "Of some mere thoughtless maze. And if in days",
      "Of dreamless dearth the plight of worried fret should pose,",
      "Perhaps with perfumed diminuendo, trace",
      "This one small peace of grace: the green day grows",
      "Slow through tunnl'd emerald elms with pace",
      "Assured, to look beyond as tranquil glows",
      "The sapphire sky to grandnew canopies of space.",
    ],
  },
  {
    author: "Tom Kuhn",
    title: "A Rose, The Last",
    poemLines: [
      "A rose, the Last, is warmed by sun's soft rays",
      "Through and through, yet quickly warmth does cool",
      "And freeze the rose's full-bloomed petals; days",
      "Are frosted into bitter nights, which pull",
      "Rubescence from its soul; and thus chaudron",
      "Of brightest hue, becomes, in turn, cold grey.",
      "And leaves, so frozen, turn from celadon.",
      "With love 'tis so when first it's new and fey",
      "Abides, but only in one heart: so slowly ",
      "That faithful heart is broken, crushed to dust ",
      "And ice, of frozen tears once shed, lowly",
      "Now dwell where love abode in summer's lust.",
      "So don't put faith in beauty at its worst ",
      "Or you may by untrue love be cursed.",
    ],
  },
  {
    author: "Tom Kuhn",
    title: "O Rose of Grace",
    poemLines: [
      "O rose of Grace my eyes have faintly traced",
      "The gemlike colors of your rainbow hues",
      "And gently glimmered in the purpled blues",
      "That cast their gleaming rays with measured haste",
      "And pushed my mind with rounded taste",
      "That ringed the eucharistic wined views",
      "And trained my mind with varied careful cues",
      "To merit love that taught beyond mere haste ",
      "And showed me circles wider than the rose",
      "(mere muse much greater than thy sweet embrace)",
      "A circle wide enough to draw me in imbues -",
      "Enthralls - entrances what now for waste Was once enchanted.",
      "Then the vortex kind Leaves all the fleeting plights of fear behind",
    ],
  },
];
