import { TPoems } from "src/types";

export const poems: TPoems = [
  {
    id: "0",
    isCover: true,
    createdTime: "12/20/1984",
    date: { start_date: "06/01/2023" },
    type: ["Post"],
    status: ["Public"],
    slug: "cover",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "Looking at the Rose Through World-Colored Glasses",
    poem: [
      "This title is from a line in Lawrence Ferlinghetti's book, Poetry as Insurgent Art.",

      "It is Dedicated to my two hero-editors, Richard Corson and Linda Hesselink. Much like scholars who deciphered The Rosetta Stone and Dead Sea scrolls, they were able to Transpose my pseudo-Mesopotamese scrawl into legible English. Also, many thanks to all of poet-teacher friends At Poetry Promise, and also to Bruce Isaacson and Izzy Bellinghausen. Many thanks to you all.",
    ],
    fullWidth: false,
    thumbnail: "src/assets/images/cover.png",
  },
  {
    id: "1",
    createdTime: "12/20/1984",
    date: { start_date: "12/20/1984" },
    type: ["Post"],
    status: ["Public"],
    slug: "soulful-heart",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "Soulful Heart",
    poem: [
      "If from this soulful heart one little rose",
      "Might bloom its petal'd hope of fragrant rays",
      "Into the tired tangled frazzled haze",
      "Of one bewildered mind; then I suppose",
      "This life is not a fragmentary close",
      "Of some mere thoughtless maze. And if in days",
      "Of dreamless dearth the plight of worried fret should pose,",
      "Perhaps with perfumed diminuendo, trace",
      "This one small peace of grace: the green day grows",
      "Slow through tunnl'd emerald elms with pace",
      "Assured, to look beyond as tranquil glows",
      "The sapphire sky to grandnew canopies of space.",
    ],
    fullWidth: false,
  },
  {
    id: "2",
    createdTime: "12/20/1984",
    date: { start_date: "12/20/1984" },
    type: ["Post"],
    status: ["Public"],
    slug: "a-rose-the-last",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "A Rose, The Last",
    poem: [
      "A rose, the Last, is warmed by sun's soft rays",
      "Through and through, yet quickly warmth does cool",
      "And freeze the rose's full-bloomed petals; days",
      "Are frosted into bitter nights, which pull",
      "Rubescence from its soul; and thus chaudron",
      "Of brightest hue, becomes, in turn, cold grey.",
      "And leaves, so frozen, turn from celadon.",
      "With love 'tis so when first it's new and fey",
      "Abides, but only in one heart: so slowly ",
      "That faithful heart is broken, crushed to dust ",
      "And ice, of frozen tears once shed, lowly",
      "Now dwell where love abode in summer's lust.",
      "So don't put faith in beauty at its worst ",
      "Or you may by untrue love be cursed.",
    ],
    fullWidth: false,
  },
  {
    id: "3",
    createdTime: "12/20/1984",
    date: { start_date: "12/20/1984" },
    type: ["Post"],
    status: ["Public"],
    slug: "o-rose-of-grace",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "O Rose of Grace",
    poem: [
      "O rose of Grace my eyes have faintly traced",
      "The gemlike colors of your rainbow hues",
      "And gently glimmered in the purpled blues",
      "That cast their gleaming rays with measured haste",
      "And pushed my mind with rounded taste",
      "That ringed the eucharistic wined views",
      "And trained my mind with varied careful cues",
      "To merit love that taught beyond mere haste ",
      "And showed me circles wider than the rose",
      "(mere muse much greater than thy sweet embrace)",
      "A circle wide enough to draw me in imbues -",
      "Enthralls - entrances what now for waste Was once enchanted.",
      "Then the vortex kind Leaves all the fleeting plights of fear behind",
    ],
    fullWidth: false,
  },
  {
    id: "4",
    createdTime: "12/20/1984",
    date: { start_date: "12/20/1984" },
    type: ["Post"],
    status: ["Public"],
    slug: "o-rose-of-mahler",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "O Rose of Mahler",
    poem: [
      "O rose of Mahler know the fleeting breath",
      "Of brilliant pain - you heard it screeching from behind",
      "And quelling all the quiet with white death",
      "You knew it could not blithely stop this blind",
      "Poor dearth of love. And yet your buds bequeath",
      "To us the glowing rays of beauty's mind",
      "It petal'd like the plum peach snow to leave",
      "The trees in Spring. Your thorn is not inclined",
      "To ease this hurtful dread. The vortex blooms",
      "Its layers upward sending healing kind",
      "Through outward-spiraled stars beyond: it looms",
      "Above this night-enlightened heart enshrined:",
      "The resurrection rose - bright our hope's own light",
      "Unfoldings growing wider than the white",
    ],
    fullWidth: false,
  },
  {
    id: "5",
    createdTime: "12/20/1984",
    date: { start_date: "12/20/1984" },
    type: ["Post"],
    status: ["Public"],
    slug: "white-rose",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "White Rose",
    poem: [
      "O'Keeffe's white rose like Stein's is touched",
      "With certain feelings: senses rise to soft",
      "Unfoldings - Cummings' \"petal of somewhere' clutched.\"",
      "Embraced my musing thought. To stars aloft",
      "My love would soar as if some quite silent",
      "And silver Sylvan were wrapped about my heart",
      "As this phosphorescent rose enclasps, relents",
      "Its quest upon my mind. And would it start",
      "Unrolling, were I Frost, I'd still stay free ",
      "To see the slow and radiant unfolding light",
      "Of this bright rose - Aurora's ecstacy.",
      "To Frost a rose is mere family, in spite",
      "Of Frost I side with Stein and must disclose",
      'Her creed as mine: "a rose is a rose is a rose."',
    ],
    fullWidth: false,
  },
  {
    id: "6",
    createdTime: "12/20/1984",
    date: { start_date: "12/20/1984" },
    type: ["Post"],
    status: ["Public"],
    slug: "sound-too-bright",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "Sound Too Bright",
    poem: [
      "Clear water's rose-white sunlight glows: sound too bright",
      "The light to sound, to rose it grows and slowly knows",
      "Her silver mirrored sound will sunset close -",
      "But not the light. It stays and plays across the height ",
      "Of heav'n - too brief this fluid flight ",
      "From sound relight to sound delight resounds",
      "Like northern lights ascending bright and quite",
      "Flowing harplike strings the colored wave astounds",
      "And glowing - these clear tears more waters pose",
      "To silvered rose bestowing goes",
      "Beyond mere platinum light -it quite rebounds",
      "Its brilliancy of knowing halcyon rounds:",
      "And rings of hope's rays sing and rose",
      "Will send with grace a grand new space: of repose",
    ],
    fullWidth: false,
  },
  {
    id: "7",
    createdTime: "12/20/1984",
    date: { start_date: "12/20/1984" },
    type: ["Post"],
    status: ["Public"],
    slug: "deep-inside",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "Deep Inside",
    poem: [
      "Somewhere deep inside your farhard icebox heart",
      "There lurks a tiny spark of star to worm",
      "Its gnarl of squirm and mar the bleating journey's firm",
      "Treading of that icebloke–comes with horse-drawn cart",
      "Who bears what's left on catafalque to bier",
      "And bury the melted with one more part–sere",
      "A heart to hearse: a cart to curse and worse",
      "You tore those souls apart–so byronic quite ironic mere",
      "Monstrosity of war–a vile dark gore.",
      "You gave your heart to the iceknave-it melted gone.",
      "Like mist at dawn–a dearth in death–he bore",
      "You away before I could stop him, alas my heart, the tear.",
      "You thought you were my hero, some big brave don juan",
      "There is nothing save grave roses for a black swan.",
    ],
    fullWidth: false,
  },
  {
    id: "8",
    createdTime: "12/20/1984",
    date: { start_date: "12/20/1984" },
    type: ["Post"],
    status: ["Public"],
    slug: "glaubenrose",
    author: [
      {
        id: "1",
        name: "Tom Kuhn",
      },
    ],
    title: "Glaubenrose",
    poem: [
      "Es ist eine Glaubenrose, a rose",
      "Of belief - of fifty summers' blistered heat -",
      "A scorching drought - and winters' frozen, of snows",
      "Yet again each spring it fulsome blooms, replete",
      "A white so phosphorescent that it glows",
      "At night. This rose, if it could talk, would say",
      '"I am still here!" A rose from Hildegard,',
      "From Guadalupe (saints), from Aelred (gay!)",
      "Its tap root reaches water table no ritard",
      "The branches stretch so high as if to say:",
      '"Can\'t touch me!" Belief still stands (no small feat)',
      "My Credo: thorn and blossom Glaubenrose -",
      "This truth from the cradle to the tomb",
      'The thorn is as persistent as the bloom."',
    ],
    fullWidth: false,
  },
];
